---
- hosts: all
  remote_user: rsetsousa
  become: yes
  tasks:
    - name: Set timezone to  SP/BR
      timezone:
        name: America/Sao_Paulo    

    - name: Instalando Apache e PHP
      apt: 
       state: present
       update_cache: yes
       pkg: 
         - apache2
         - php-curl
         - php-gd
         - php-mbstring
         - php-xml
         - php-xmlrpc
         - php-soap
         - php-intl
         - php-zip
         - php
         - libapache2-mod-php
         - php-mysql
         - mysql-client


    - name: Download WordPress
      get_url:
        url=https://wordpress.org/latest.tar.gz
        dest=/tmp/wordpress.tar.gz
        validate_certs=no

    - name: Desempacotando o TAR do Wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        owner: www-data
        group: www-data
        copy: no

    - name: Configurando o Apache
      lineinfile:
        dest=/etc/apache2/sites-enabled/000-default.conf
        regexp="(.)+DocumentRoot /var/www/html"
        line="DocumentRoot /var/www/wordpress"
      notify:
        - restart apache

    - name: Configurando o Wordpress (Banco de Dados)
      template:
        src: /vagrant/wp-config.j2
        dest: /var/www/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: '0644'

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

